### ISSUE TITLE
JDA - Time slider in time and place view not showing correct results

### ISSUE THREAD

**Issue by lfbrandao** [Japan-Digital-Archives/Japan-Digital-Archive#9] opened 2012-03-13 04:34 UTC
to reproduce:

search 海
3326 hits

switch to time and place view, filter for any time span
looks like the map is updating correctly, but results number remains the same. Shouldn't it show the number of results at any given time filter? Moved from the Zeega repository - https://github.com/Zeega/Zeega-Core/issues/495

**Comment by kanarinka** [comment] 2012-03-13 20:44
Closing - this is duplicate of what I just posted. The slider works fine but the results count is not updating.

**Closed as completed by kanarinka** 2012-03-13 20:44 UTC
Labels: high priority
