### ISSUE TITLE
testimonial pop-up:: tag N;

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#927] opened 2015-02-14 00:14 UTC
We got some testimonial submissions, ID1953896~195390, &1953903.
In their pop-ups, N; tags are showing up when there is no tag in the fancybox as well as in their item pages.
Expample ID1953896
Edit page: http://jdarchive.org/admin/zeega/data/item/1953896/edit
Item page: http://jdarchive.org/en/item/1953896

![n tag problem in testimonials](https://cloud.githubusercontent.com/assets/8831502/6197419/da612ebc-b3b2-11e4-9434-a586f59bf82f.png)

**Comment by corinnecurcie** [comment] 2015-02-20 19:33
Hey Koko,

The problem is fixed in that "N;" tags won't show up anymore on the site - sometimes they may show on the backend still (for example if you add a tag to one of the N;-tagged items, even though the N; tag wasn't previously showing up in admin dashboard, the N; tag and the new tag will then show up on the dashboard.) 

I'm going to work on editing the testimonial submission form so that we don't get the N; error but for now on the front end this problem is fixed.

**Closed as completed by corinnecurcie** 2015-02-20 19:33 UTC

**Comment by jdaKoko** [comment] 2015-02-20 23:43
Thanks again!
