### ISSUE TITLE
My collection page: dragged items are not loading, cannot edit.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1017] opened 2015-10-28 21:57 UTC
@meeshmon @jcuanm 
1.) Items are not loading to collection pages
2.) Editing function is not working
http://jdarchive.org/en/collection/1998442
![screen shot 2015-10-29 at 6 42 05 am](https://cloud.githubusercontent.com/assets/8831502/10804252/e43ab378-7e09-11e5-9577-42d4695e9303.png)

**Comment by meeshmon** [comment] 2015-10-29 00:12
Also @rchen152 and @horak can one of you take a look?

**Comment by rchen152** [comment] 2015-10-29 04:20
Wondering if it might be this:
https://theeventscalendar.com/support/forums/topic/uncaught-invalidvalueerror-not-an-object/
If you go to http://dev.jdarchive.org/rebecca/web/en/search#view_type=thumb&media_type=Collection& and try to load some of the collections, the first three are just fine, while the fourth one (http://dev.jdarchive.org/rebecca/web/en/collection/884991)
causes the error
Uncaught InvalidValueError: not an Object
to be logged to the console, and the editing and item loading are broken.

**Comment by rchen152** [comment] 2015-10-29 05:13
Ok, I'm not getting anywhere with this - will come back to it in a few days when I have more time.  If anyone else wants to take a look in the meantime, the snippet of code that causes the error to be thrown is the following from web/js/app/views/items/jda.view.item.collection-page.js:
new google.maps.LatLng(this.model.get("media_geo_latitude"),this.model.get("media_geo_longitude"))

It blows up when this.model.get("media_geo_latitude") or this.model.get("media_geo_longitude") is null, but I'm not sure how to determine whether (1) a change to the GoogleMaps API caused the values to be incorrectly set to null elsewhere, and this is just one symptom of the problem, or (2) the values are indeed supposed to be null, and the problem is just that google.maps.LatLng used to accept null values and no longer does (so we need to check for them ourselves).

**Comment by rchen152** [comment] 2015-11-02 23:27
Ryo and I troubleshooted this during today's tech meeting, and it should be fixed now.

**Closed as completed by rchen152** 2015-11-02 23:27 UTC

**Comment by jdaKoko** [comment] 2015-11-03 22:24
Thank you!
