### ISSUE TITLE
No Collection is appearing on the JDA site.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#996] opened 2015-09-01 01:51 UTC
The collection page is not loading any collections.  No collection is appearing the top page.

**Comment by jdaKoko** [comment] 2015-09-01 01:52
![no collection](https://cloud.githubusercontent.com/assets/8831502/9594584/9a3720c0-502a-11e5-8558-fc61342699ba.png)

**Comment by meeshmon** [comment] 2015-09-01 04:54
@corinnecurcie @horak 
can you guys take a quick look to see what the problem is?

**Comment by horak** [comment] 2015-09-01 12:01
@meeshmon, @corinnecurcie I'm 500 on network requests and getting :

`"Solr HTTP error: HTTP request failed"`

Unfortunately restarting solr doesn't fix the problem. Still investigating.

**Comment by horak** [comment] 2015-09-01 12:13
Getting this guy ![solr](https://cloud.githubusercontent.com/assets/1111424/9603820/5fbb6b0c-5081-11e5-9664-f790d515a0d9.png)

**Comment by nickkapur** [comment] 2015-09-01 19:35
This is odd. Collections were working fine on Friday! Normally we fixed this by simply restarting/reindexing Solr. That is usually pretty easy. Is the problem here that we cannot even restart Solr?

**Comment by nickkapur** [comment] 2015-09-01 20:00
Oh, okay, I see. Somehow the SolrCores are not being recognized. So either you would need to create the cores, or change the <cores> part of the solr.xml file located at the root of where your Solr index is running, so that Solr can recognize the cores.

Some more info is here: http://wiki.apache.org/solr/CoreAdmin

**Comment by horak** [comment] 2015-09-02 15:05
Thanks @nickkapur, so using that resource I tried creating the cores using 

```
http://localhost:8080/solr/admin/cores?action=CREATE&name=zeega&instanceDir=zeega
```

but that just gives me the same problem:

```
<response>
<lst name="responseHeader">
<int name="status">0</int>
<int name="QTime">0</int>
</lst>
<str name="defaultCoreName">zeega</str>
<lst name="initFailures">
<str name="zeega">
org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Error Instantiating Update Handler, solr.DirectUpdateHandler2 failed to instantiate org.apache.solr.update.UpdateHandler
</str>
</lst>
<lst name="status"/>
</response>
```

I don't know where else I'd point `instanceDir` towards, it seems to be pointing to the right place. I think the problem rests with the `updateHandler`. I think the solr instance just crashed somewhere in executing this update and is unable to restart because of the same problem. I commented out the `updateHandler class="solr.DirectUpdateHandler2"` and the solr core is back up and running but that certainly isn't a permanent fix. What makes this strange is that the `updateHandler` is implemented in the most vanila way possible which to me points to some more insidious problem. Any ideas?

edit:
Also, just to have it on record. [Here](https://gist.github.com/horak/34b9c176ba729fd559fa) is the method, prior to my edits, I commented out within `solrconfig.xml`. So that is the original; currently all those uncommented lines are commented out.

edit2:
I've returned the `solrconfig.xml` to it's previous state and the initial problem the `DirectUpdateHandler2` seemed to have been causing has vanished. Steve & I are investigating memory related problems instead.

**Comment by nickkapur** [comment] 2015-09-02 16:23
Yikes. This seems a bit crazier than anything we had to deal with before. That said, Solr was always crapping out on us and needing to be reindexed at random times, even when we hadn't pushed any updates in weeks or months, so I have a very poor and very lasting impressing of Solr and its instability.

**Comment by corinnecurcie** [comment] 2015-09-02 16:26
Hey all, 
Sorry for my lack of responses. I will take a look at this tonight after work!

**Comment by jdaKoko** [comment] 2015-09-02 16:45
Just for the record:
Dear Alex,

Thank you for working to fix the problem.

It seems the JDA site was working a little while ago (9.2.15 around 11:00 am), but the total search item number was missing about 18,689 items.
Recently made collections were not appearing on the collection page.
The Headline (user 426) and RIJS (user 1) items were missing about 18,677 items from the JDA search.  I could not search for all of the missing items because things are not loading again.
If you could look into the problem again, I'd appreciate it very much.

Best,
Koko

**Comment by horak** [comment] 2015-09-02 17:13
Ok got it back up but definitely needs to be re-indexed, which i'm doing now.

**Comment by horak** [comment] 2015-09-02 19:49
@jdaKoko can you tell me where you are getting that total count? I re-indexed a few times but it keeps breaking :/

**Comment by jdaKoko** [comment] 2015-09-02 20:58
@horak Right now, the total count of published items on the admin page is 1,479,775.

**Comment by jdaKoko** [comment] 2015-09-02 22:13
@horak 
FYI
It seems > id1971038 are not appearing on the search.

**Comment by horak** [comment] 2015-09-02 22:59
Still unable to re-index ugh

**Comment by meeshmon** [comment] 2015-09-03 16:52
@corinnecurcie did you have a chance to take a look?

**Comment by horak** [comment] 2015-09-03 16:55
I finally got a re-index to succeed.

![screenshot at sep 03 11-21-41](https://cloud.githubusercontent.com/assets/1111424/9664541/321998d0-5230-11e5-82d1-769573ea3a95.png)

**Comment by jdaKoko** [comment] 2015-09-03 16:59
Thank you very much!
![hooray](https://cloud.githubusercontent.com/assets/8831502/9665039/99b07f44-523b-11e5-9867-577532b1ff84.png)

**Comment by horak** [comment] 2015-09-03 20:06
Unfortunately I'm still seeing lots of errors @jdaKoko, have you checked the total item count? I don't think they're accurate :/

**Comment by corinnecurcie** [comment] 2015-09-04 00:32
I took a look last night, and it's definitely a more extreme problem than most things we've dealt with before... I wasn't able to figure out much, but I can look again tonight. Have you updated any apache or solr stuff Alex? The last time the database broke this badly was because I was prompted to update one of them upon logging into the production server, and I was naive and thought updating was a good thing, but it broke everything, and I had to go make sure all my schema/config files were in line with the new version before anything would work again, so that might be something to investigate.

**Comment by meeshmon** [comment] 2015-09-04 03:17
Ok good to know that this is an extreme problem. I mean not good but at least we know this needs a serious attention. Do let us know if you find more about this, and what you think the issue might be. Any input would be helpful to think about where to go from here.

**Comment by jdaKoko** [comment] 2015-09-04 04:09
@horak 
Total account results in 3 items missing.  Right now (9.4.15 @ 12:06 am) it should be 1480312, but it is 1,480,309.  I cannot trace which ones are missing. The total number changes very frequently because people sumit items every day.

**Comment by jdaKoko** [comment] 2015-09-04 11:57
Sorry, the site is down again.

**Comment by horak** [comment] 2015-09-04 23:39
brought it back up earlier today @jdaKoko. @corinnecurcie, I didn't, in fact I hadn't touched a thing in quite a while. Just got @spacemansteve looped in, feel free to ask for any clarification, the above should give you an idea of what's going on though.

**Comment by spacemansteve** [comment] 2015-10-05 22:39
As noted at https://github.com/Japan-Digital-Archives/Japan-Digital-Archive, Alex and SpacemanSteve increased Solr's ram from 128mb to 256mb on Sept 18th.  SpacemanSteve had to restart Solr again on Sept 19th.  There has been no incident or problem with it in over two weeks.  If there are no problems soon, I will suggest closing this issue.

**Comment by horak** [comment] 2015-10-05 22:48
Yeah I think we should go ahead and close it. We can reopen if problems arise. I'm really glad that seemed to have done the trick (and very surprised).

**Closed as completed by horak** 2015-10-05 22:48 UTC
Labels: bug, high priority

**Comment by nickkapur** [comment] 2015-10-06 06:57
Glad to know this is working! :)
